### ISSUE TITLE
Privilege separation

### ISSUE THREAD

**Issue by mmaridev** [webvalley/wv-mongo-docker#1]
Gather some docs to understand if Mongo nativley supports privilege separation. The goal is to require access for every table and grant access to the sensible informations just to a specific group of users.

**Comment by LeonardoDusini** [comment]
guide on mongo roles

https://docs.mongodb.com/manual/reference/built-in-roles/

**Comment by LeonardoDusini** [comment]
user assigned roles and management

https://docs.mongodb.com/manual/tutorial/manage-users-and-roles/

**Comment by LeonardoDusini** [comment]
definition of user doctor

**Comment by LeonardoDusini** [comment]
definition of user doctor


[admin_user.txt](https://github.com/webvalley/wv-mongo-docker/files/3338230/admin_user.txt)

**Comment by LeonardoDusini** [comment]
[normal_user.txt](https://github.com/webvalley/wv-mongo-docker/files/3338309/normal_user.txt)

**Comment by LeonardoDusini** [comment]
[normal_user_updated.txt](https://github.com/webvalley/wv-mongo-docker/files/3341646/normal_user_updated.txt)

**Comment by LeonardoDusini** [comment]
all of what we need for refs
https://docs.mongodb.com/manual/reference/database-references/

**Comment by mmaridev** [comment]
```
use plic;

db.createRole({
  role: "doctor",
  privileges: [{
    resource: {db: "plic", collection: ""},
    actions: [ "find", "update", "insert", "remove"],
  }],
  roles: []
});

db.createRole({
  role: "researcher",
  privileges: [{
    resource: {db: "plic", collection: "milan"},
    actions: [ "find", "update", "insert", "remove"],
  }],
  roles: []
});

db.createUser({
	user: "dr_chierici",
	pwd: "MarcoIlPianista",
	roles: [{role: "doctor", db: "plic"}]
});

db.createUser({
	user: "beatrice",
	pwd: "Biostatistica",
	roles: [{role: "researcher", db: "plic"}]
});
```

To test:
```
$ mongo --port 27017 -u dr_chierici -p MarcoIlPianista --authenticationDatabase plic
use plic;
db.milan.find({});
db.pat_names.find({});

$ mongo --port 27017 -u beatrice -p Biostatistica --authenticationDatabase plic
db.milan.find({});
db.pat_names.find({}); # Raises unauthorized
```

**Comment by LeonardoDusini** [comment]
[manual_ref.txt](https://github.com/webvalley/wv-mongo-docker/files/3344424/manual_ref.txt)

manual refs
